version: '3.9'
services:
  conta_pagar:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
      args:
        TESTS_DIR: ContasPagar
        PYTESTMARK: dockerContaPagar  # Ajuste para passar o valor correto para o pytest
    image: HosAnalise/conta_pagar:latest

  conta_receber:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
      args:
        TESTS_DIR: ContasReceber
        PYTESTMARK: dockerContaReceber  # Ajuste para passar o valor correto para o pytest
    image: HosAnalise/conta_receber:latest
