version: '1.0'
services:
  dockerContasPagar:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ContasPagar
        PYTESTMARK: dockerContasPagar
    image: hosanalise/dockerContasPagar:latest
  dockerContasReceber:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ContasReceber
        PYTESTMARK: dockerContasReceber
    image: hosanalise/dockerContasReceber:latest
  dockerConciliacaoBancaria:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ConciliacaoBancaria
        PYTESTMARK: dockerConciliacaoBancaria
    image: hosanalise/dockerConciliacaoBancaria:latest
  dockerCreditoCliente:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: CreditoCliente
        PYTESTMARK: dockerCreditoCliente
    image: hosanalise/dockerCreditoCliente:latest
  dockerExtratoDeContas:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ExtratoDeContas
        PYTESTMARK: dockerExtratoDeContas
    image: hosanalise/dockerExtratoDeContas:latest
  dockerCreditoFornecedor:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: CreditoFornecedor
        PYTESTMARK: dockerCreditoFornecedor
    image: hosanalise/dockerCreditoFornecedor:latest
  dockerCheques:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: Cheques
        PYTESTMARK: dockerCheques
    image: hosanalise/dockerCheques:latest
  dockerCadastroPessoas:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: CadastroPessoas
        PYTESTMARK: dockerCadastroPessoas
    image: hosanalise/dockerCadastroPessoas:latest
