services:
  conta_pagar:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ContasPagar
        PYTESTMARK: dockerContaPagar  
        
    image: hosanalise/conta_pagar:latest
    environment:
      - APPLITOOLS_API_KEY=${APPLITOOLS_API_KEY}


  conta_receber:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ContasReceber
        PYTESTMARK: dockerContaReceber  
    image: hosanalise/conta_receber:latest
    environment:
      - APPLITOOLS_API_KEY=${APPLITOOLS_API_KEY}

    
  conciliacao_bancaria:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ConciliacaoBancaria
        PYTESTMARK: dockerConciliacaoBancaria  
    image: hosanalise/conciliacao_bancaria:latest
    environment:
      - APPLITOOLS_API_KEY=${APPLITOOLS_API_KEY}


  extrato_contas:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ExtratoDeContas
        PYTESTMARK: dockerExtratoDeContas  
    image: hosanalise/extrato_contas:latest
    environment:
      - APPLITOOLS_API_KEY=${APPLITOOLS_API_KEY}




