version: '1.0'
services:
  dockercontaspagar:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ContasPagar
        PYTESTMARK: dockerContasPagar
    image: hosanalise/dockercontaspagar:latest
  dockercontasreceber:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ContasReceber
        PYTESTMARK: dockerContasReceber
    image: hosanalise/dockercontasreceber:latest
  dockerconciliacaobancaria:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ConciliacaoBancaria
        PYTESTMARK: dockerConciliacaoBancaria
    image: hosanalise/dockerconciliacaobancaria:latest
  dockercreditocliente:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: CreditoCliente
        PYTESTMARK: dockerCreditoCliente
    image: hosanalise/dockercreditocliente:latest
  dockerextratodecontas:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: ExtratoDeContas
        PYTESTMARK: dockerExtratoDeContas
    image: hosanalise/dockerextratodecontas:latest
  dockercreditofornecedor:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: CreditoFornecedor
        PYTESTMARK: dockerCreditoFornecedor
    image: hosanalise/dockercreditofornecedor:latest
  dockercheques:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: Cheques
        PYTESTMARK: dockerCheques
    image: hosanalise/dockercheques:latest
  dockercadastropessoas:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TESTS_DIR: CadastroPessoas
        PYTESTMARK: dockerCadastroPessoas
    image: hosanalise/dockercadastropessoas:latest
