[pytest]
markers =
    
    dockerContasPagar : Contas a pagar é o modulo que lista todas as contas a pagar do sistema.
    dockerContasReceber
    dockerConciliacaoBancaria
    dockerCreditoCliente
    dockerExtratoDeContas
    dockerCreditoFornecedor
    dockerCheques
    dockerCadastroPessoas
    dockerMetasPorRegiao
    

norecursedirs = testes/desktop



