[pytest]
markers =
    
    dockerContasPagar : Contas a pagar é o modulo que lista todas as contas a pagar do sistema.
    dockerContasReceber : Contas a receber é o modulo que lista todas as contas a receber do sistema.
    dockerConciliacaoBancaria : Conciliação bancária é o módulo que realiza a conciliação das contas bancárias.
    dockerCreditoCliente : Crédito do cliente é o módulo que gerencia o crédito disponível para os clientes.
    dockerExtratoDeContas : Extrato de contas é o módulo que gera o extrato das contas do sistema.
    dockerCreditoFornecedor : Crédito do fornecedor é o módulo que gerencia o crédito disponível para os fornecedores.
    dockerCheques : Cheques é o módulo que gerencia os cheques emitidos e recebidos.
    dockerCadastroPessoas : Cadastro de pessoas é o módulo que gerencia o cadastro de clientes e fornecedores.
    dockerMetasPorRegiao : Metas por região é o módulo que gerencia as metas de vendas por região.

norecursedirs = testes/desktop



