[pytest]
markers =
    
    dockerContasPagar
    dockerContasReceber
    dockerConciliacaoBancaria
    dockerCreditoCliente
    dockerExtratoDeContas
    dockerCreditoFornecedor
    dockerCheques
    dockerCadastroPessoas
    dockerMetasPorRegiao
    

norecursedirs = testes/desktop



