name: Docker Compose Build and Push

on:

  push:
    branches:
      - prod
    paths:
      # O trigger agora também observa a pasta de scripts,
      # caso uma mudança no script de build precise gerar um novo deploy.
      - 'classes/rotinas/**'
      - 'docker-compose.yml'
      - 'scripts/**'
      - 'testes/web/**'


jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        # Usando a versão mais recente e segura do action
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        # Usando a versão mais recente e segura do action
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     

      - name: Build das imagens do Docker Compose
        # Apenas constrói as imagens, sem iniciar os contêineres.
        # É mais rápido e focado para CI.
        run: docker-compose build

    

      