name: Docker Compose Build and Push

on:
  push:
    branches:
      - prod
    paths:
      - 'docker-compose.yml'
     

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build todas imagens com docker-compose
        run: docker-compose build

      - name: Push imagens do docker-compose
        run: |
          IMAGES=$(docker-compose config | grep 'image:' | awk '{print $2}')
          for IMAGE in $IMAGES; do
            docker push $IMAGE
          done
